[[news]]
date = "2025-09"
content = "Started as an HQI Prize Fellow at Harvard University and a joint postdoctoral fellow at MIT."

[[news]]
date = "2025-08"
content = "Completed my PhD in Physics at UC Berkeley under the supervision of Michael P. Zaletel."

[[news]]
date = "2025-07"
content = "Posted three preprints on chiral superconductivity, quantum criticality, and edge reconstruction in quantum Hall systems."

[[news]]
date = "2024-06"
content = "Completed a Graduate Fellowship at the Kavli Institute for Theoretical Physics (KITP)."
